#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-ncclient
Version  : 0.6.12
Release  : 1
URL      : https://files.pythonhosted.org/packages/b4/fb/ea6e42afdc51e7f3db3df07e380617e878eba53fc4afb9c155474e4ca904/ncclient-0.6.12.tar.gz
Source0  : https://files.pythonhosted.org/packages/b4/fb/ea6e42afdc51e7f3db3df07e380617e878eba53fc4afb9c155474e4ca904/ncclient-0.6.12.tar.gz
Summary  : Python library for NETCONF clients
Group    : Development/Tools
License  : Apache-2.0
Requires: pypi-ncclient-license = %{version}-%{release}
Requires: pypi-ncclient-python = %{version}-%{release}
Requires: pypi-ncclient-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(lxml)
BuildRequires : pypi(paramiko)
BuildRequires : pypi(selectors2)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(six)

%description
--------------------------------------------
        
        ncclient is a Python library that facilitates client-side scripting and
        application development around the NETCONF protocol. ``ncclient`` was

%package license
Summary: license components for the pypi-ncclient package.
Group: Default

%description license
license components for the pypi-ncclient package.


%package python
Summary: python components for the pypi-ncclient package.
Group: Default
Requires: pypi-ncclient-python3 = %{version}-%{release}

%description python
python components for the pypi-ncclient package.


%package python3
Summary: python3 components for the pypi-ncclient package.
Group: Default
Requires: python3-core
Provides: pypi(ncclient)
Requires: pypi(lxml)
Requires: pypi(paramiko)
Requires: pypi(selectors2)
Requires: pypi(setuptools)
Requires: pypi(six)

%description python3
python3 components for the pypi-ncclient package.


%prep
%setup -q -n ncclient-0.6.12
cd %{_builddir}/ncclient-0.6.12

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1639056157
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-ncclient
cp %{_builddir}/ncclient-0.6.12/LICENSE %{buildroot}/usr/share/package-licenses/pypi-ncclient/2b8b815229aa8a61e483fb4ba0588b8b6c491890
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-ncclient/2b8b815229aa8a61e483fb4ba0588b8b6c491890

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
